### PR TITLE
Fix arg name

### PR DESCRIPTION
**Pull request by medecau**
PLEASE, for the love of all good things DO NOT disable warnings OR if you do PLEASE understand what you are doing!

Here's the docs: https://docs.python.org/3/library/os.html#os.makedirs

### CODE REVIEW

**Comment by de-code** [comment]
Hi @medecau thank you for your contributions.

In my defence, this came from a time when I still had to support Python 2 as well (which is why the warning was ignored). But I don't have any excuse for not having checked the parameter correctly. Sorry. (I will apply your fix, thank you for spotting it)

Out of curiosity, are you using this library directly or indirectly?

**Review by de-code — APPROVED** [review]

**Comment by de-code** [comment]
On a further thought, the `makedirs` method should probably be removed, but could also be done as a separate PR. With only supporting Python 3, there is no advantage over `os.makedirs` (or the equivalent from `pathlib`)

**Comment by medecau** [comment]
We were using this from https://github.com/elifesciences/sciencebeam and getting some errors around this - can't remember details. We're now using Grobid directly though.

Totally agree with the assertion that you do not need this util and can use `os.makedirs` directly.

_Sorry if the OP comes out a bit aggressive. I should be nicer than this. 🙏_

**Comment by de-code** [comment]
> We were using this from https://github.com/elifesciences/sciencebeam and getting some errors around this - can't remember details. We're now using Grobid directly though.

In that case thank you for your time even though you are not using it anymore. You might be interested that we recently started https://github.com/elifesciences/sciencebeam-parser as an alternative to GROBID. Although our main focus will be author submitted manuscripts.

> _Sorry if the OP comes out a bit aggressive. I should be nicer than this. pray_

No offence taking. I am annoyed by sloppy code myself and the block of code clearly wasn't setting a good example.

**Pull request merged**
